In [1]:
import scanpy as sc
import numpy as np

In [2]:
# Creating a random matrix with 5 rows for observations (cells) and 3 columns for variables (genes)
adata = sc.AnnData(X=np.random.rand(5, 3))
adata

AnnData object with n_obs × n_vars = 5 × 3

In [3]:
adata.X

array([[0.44553164, 0.53237194, 0.19820757],
       [0.14540816, 0.65610779, 0.8645768 ],
       [0.04377226, 0.20556402, 0.87213767],
       [0.19022053, 0.10529168, 0.34080046],
       [0.39752133, 0.71550259, 0.95998465]])

In [4]:
adata.obs_names = ['cell_1', 'cell_2', 'cell_3', 'cell_4', 'cell_5']
adata.var_names = ['gene_1', 'gene_2', 'gene_3']

In [5]:
adata.obs['cell_type'] = ['A', 'B', 'A', 'B', 'C'] 
adata.var['cell_count'] = [500, 120, 100]
adata.var['highly_variable'] = [False, True, True]

In [6]:
adata

AnnData object with n_obs × n_vars = 5 × 3
    obs: 'cell_type'
    var: 'cell_count', 'highly_variable'

In [7]:
# Add mock PCA results
adata.obsm['X_pca'] = np.random.rand(5, 2)  # 5 observations, 2 PCA components

# Add some mock metadata
adata.varm['additional_info'] = np.random.rand(3, 2)  # 3 variables, 2 types of additional info

In [8]:
adata

AnnData object with n_obs × n_vars = 5 × 3
    obs: 'cell_type'
    var: 'cell_count', 'highly_variable'
    obsm: 'X_pca'
    varm: 'additional_info'

In [9]:
adata.obsm['X_pca']

array([[0.73415153, 0.55316867],
       [0.28919804, 0.69995024],
       [0.11020741, 0.96760457],
       [0.54270542, 0.11783809],
       [0.26675692, 0.52327206]])

In [10]:
adata.varm['additional_info']

array([[0.8119597 , 0.71456505],
       [0.81247594, 0.19464328],
       [0.40450844, 0.7042471 ]])

In [11]:
from scipy.spatial.distance import cdist
adata.obsp['distances'] = distances = cdist(adata.X, adata.X, 'euclidean')
adata.obsp['distances']

array([[0.        , 0.74123721, 0.8499387 , 0.51760414, 0.78494977],
       [0.74123721, 0.        , 0.46192717, 0.76141197, 0.27602799],
       [0.8499387 , 0.46192717, 0.        , 0.56019717, 0.62681165],
       [0.51760414, 0.76141197, 0.56019717, 0.        , 0.89371139],
       [0.78494977, 0.27602799, 0.62681165, 0.89371139, 0.        ]])

In [12]:
adata.varp['correlations'] = np.corrcoef(adata.X.T)
adata.varp['correlations']

array([[ 1.        ,  0.56004991, -0.38588474],
       [ 0.56004991,  1.        ,  0.36980182],
       [-0.38588474,  0.36980182,  1.        ]])

In [13]:
adata.uns['experiment_info'] = {'date': '2024-01-01', 'researcher': 'Andres Colubri'}
print(adata.uns)

OrderedDict([('experiment_info', {'date': '2024-01-01', 'researcher': 'Andres Colubri'})])


In [14]:
adata.layers['raw'] = np.random.poisson(2, (5, 3))
adata.layers['normalized'] = np.log1p(adata.layers['raw'])
print(adata.layers['normalized'])

[[1.09861229 1.09861229 0.69314718]
 [1.09861229 0.69314718 1.09861229]
 [1.79175947 1.09861229 0.        ]
 [1.60943791 0.         0.69314718]
 [0.69314718 0.69314718 0.69314718]]


In [15]:
adata

AnnData object with n_obs × n_vars = 5 × 3
    obs: 'cell_type'
    var: 'cell_count', 'highly_variable'
    uns: 'experiment_info'
    obsm: 'X_pca'
    varm: 'additional_info'
    layers: 'raw', 'normalized'
    obsp: 'distances'
    varp: 'correlations'